import { expect, test } from '@playwright/test'
import { evidencePath } from './runtime'

test('跨除权日后价位线跟随同一历史K线，缩放和刷新不漂移', async ({ page }) => {
  const active = (await (await page.request.get('/api/trainings/active')).json()).training
  if (active) await page.request.post(`/api/trainings/${active.id}/abandon`)
  const created = await page.request.post('/api/trainings', { data: { code: '300857', tier: '1M', start_date: '2026-04-21' } })
  expect(created.status()).toBe(201)
  const id = (await created.json()).training.id
  await page.goto('/')
  await expect(page.locator('.drawing-save-status')).toHaveText('已保存')
  await expect(page.getByRole('status').filter({ hasText: '正在记录' })).toBeVisible()
  const bar = await page.evaluate(() => (window as any).__trainerChart.bars().at(-1))
  const position = await page.evaluate(({ timestamp, high }) => (window as any).__trainerChart.pointToPixel(timestamp, high), bar)
  const host = await page.locator('.chart-host').boundingBox()
  await page.getByRole('combobox', { name: '吸附', exact: true }).selectOption('strong_magnet')
  await page.locator('.draw-toolbar').getByRole('button', { name: '价位线', exact: true }).click()
  await page.mouse.click(host!.x + position.x, host!.y + position.y)
  await expect.poll(() => page.evaluate(() => (window as any).__trainerChart.drawings().length)).toBe(1)
  const before = await page.evaluate(() => (window as any).__trainerChart.drawings()[0])
  expect(before.points[0].value).toBeCloseTo(bar.high, 6)
  await expect(page.locator('.drawing-save-status')).toHaveText('已保存')
  await page.getByRole('button', { name: '推进下一日', exact: true }).click()
  await expect(page.locator('.training-current-date')).toContainText('2026-04-22')
  await expect(page.locator('.loading-dot')).not.toBeVisible()
  const afterPayload = await (await page.request.get(`/api/trainings/${id}/bars?tf=1D`)).json()
  const anchorBar = afterPayload.bars.find((item: { date: string }) => item.date === bar.date)
  expect(anchorBar.high).not.toBeCloseTo(bar.high, 2)
  await expect.poll(() => page.evaluate(() => (window as any).__trainerChart.drawings()[0]?.points[0].value)).toBeCloseTo(anchorBar.high, 6)
  const current = await page.evaluate(() => (window as any).__trainerChart.drawings()[0])
  // Pure axis scaling changes projection, never the stored price or timestamp.
  const box = await page.locator('.chart-host').boundingBox()
  await page.mouse.move(box!.x + box!.width - 12, box!.y + 180)
  await page.mouse.wheel(0, 120)
  expect(await page.evaluate(() => (window as any).__trainerChart.drawings()[0].points)).toEqual(current.points)
  await page.screenshot({ path: evidencePath('drawing-basis-after.png') })
  await page.locator('.status-message').click()
  await page.keyboard.press('Control+z')
  await expect.poll(() => page.evaluate(() => (window as any).__trainerChart.drawings().length)).toBe(0)
  await page.keyboard.press('Control+y')
  await expect.poll(() => page.evaluate(() => (window as any).__trainerChart.drawings()[0]?.points[0].value)).toBeCloseTo(anchorBar.high, 6)
  await expect(page.locator('.drawing-save-status')).toHaveText('已保存')
  await page.reload()
  await expect(page.locator('.drawing-save-status')).toHaveText('已保存')
  await expect.poll(() => page.evaluate(() => (window as any).__trainerChart?.drawings()[0]?.points[0].value)).toBeCloseTo(anchorBar.high, 6)
  await page.getByRole('tab', { name: '周K', exact: true }).click()
  await expect(page.locator('.loading-dot')).not.toBeVisible()
  await expect.poll(() => page.evaluate(() => (window as any).__trainerChart.drawings()[0]?.points[0].value)).toBeCloseTo(anchorBar.high, 6)
})

test('空画线跨除权日后新画价位线，普通刷新不会再次复权', async ({ page }) => {
  const active = (await (await page.request.get('/api/trainings/active')).json()).training
  if (active) await page.request.post(`/api/trainings/${active.id}/abandon`)
  const created = await page.request.post('/api/trainings', { data: { code: '300857', tier: '1M', start_date: '2026-04-21' } })
  expect(created.status()).toBe(201)
  await page.goto('/')
  await expect(page.getByRole('status').filter({ hasText: '正在记录' })).toBeVisible()
  await page.getByRole('button', { name: '推进下一日', exact: true }).click()
  await expect(page.locator('.training-current-date')).toContainText('2026-04-22')
  await expect(page.getByRole('button', { name: '刷新图表', exact: true })).toBeEnabled()
  const bar = await page.evaluate(() => (window as any).__trainerChart.bars().at(-1))
  const point = await page.evaluate(({ timestamp, high }) => (window as any).__trainerChart.pointToPixel(timestamp, high), bar)
  const host = await page.locator('.chart-host').boundingBox()
  await page.getByRole('combobox', { name: '吸附', exact: true }).selectOption('strong_magnet')
  await page.locator('.draw-toolbar').getByRole('button', { name: '价位线', exact: true }).click()
  await page.mouse.click(host!.x + point.x, host!.y + point.y)
  await expect.poll(() => page.evaluate(() => (window as any).__trainerChart.drawings().length)).toBe(1)
  const drawnPrice = await page.evaluate(() => (window as any).__trainerChart.drawings()[0].points[0].value)
  expect(Math.abs(drawnPrice - bar.high)).toBeLessThanOrEqual(.02)
  await page.getByRole('button', { name: '刷新图表', exact: true }).click()
  await expect(page.getByRole('button', { name: '刷新图表', exact: true })).toBeEnabled()
  expect(await page.evaluate(() => (window as any).__trainerChart.drawings()[0].points[0].value)).toBe(drawnPrice)
  await expect(page.locator('.drawing-save-status')).toHaveText('已保存')
  await page.reload()
  await expect(page.locator('.drawing-save-status')).toHaveText('已保存')
  await expect.poll(() => page.evaluate(() => (window as any).__trainerChart?.drawings()[0]?.points[0].value)).toBe(drawnPrice)
})
