import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { CompactReader } from '../web/src/recording/compactCodec'
import { readRecordingArtifact } from './recording-file'
import { startTrainingFromForm, settleThroughConfirmation } from './training-flow'
import { evidencePath } from './runtime'

test('录制上下文准备期间不会漏掉第一笔交易', async ({ page }) => {
  const active = (await (await page.request.get('/api/trainings/active')).json()).training
  if (active) await page.request.post(`/api/trainings/${active.id}/abandon`)
  let release!: () => void
  const contextReady = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/trainings/*/recording-context', async route => { await contextReady; await route.continue() })
  await page.goto('/')
  await page.getByPlaceholder('搜索代码或名称，如 600519 或 贵州茅台').fill('600519')
  await page.getByRole('button', { name: /600519 贵州茅台/ }).click()
  await page.locator('input[type="date"]').fill('2026-09-01')
  await startTrainingFromForm(page)
  await expect(page.locator('.training-grid')).toHaveAttribute('inert', '')
  await page.keyboard.press('b')
  const before = await (await page.request.get('/api/trainings/active')).json()
  expect(before.trades).toHaveLength(0)
  release()
  await expect(page.getByRole('status').filter({ hasText: '正在记录' })).toBeVisible()
  await expect(page.locator('.training-grid')).not.toHaveAttribute('inert', '')
  await page.getByRole('button', { name: '买入', exact: true }).click()
  await expect(page.locator('.status-message')).toContainText('成交')
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出录制', exact: true }).click()
  const download = await pending
  const output = evidencePath('first-trade-recorded.json.gz')
  await download.saveAs(output)
  // 导出仅 gzip：文件头必须是 gzip magic（与扩展名/MIME 无关）
  expect([...(await readFile(output)).subarray(0, 2)]).toEqual([0x1f, 0x8b])
  const file = await readRecordingArtifact(output)
  expect(file.gaps).toEqual([])
  if (file.schemaVersion !== 2) throw Error('Expected compact recording')
  // 新录制不落创建样板事件（REC-02 口径）；首笔交易仍然恰好 started+finished 且被接受
  expect(file.events.filter((event: any) => event.action === 'training.create')).toEqual([])
  const trade = file.events.filter((event: any) => event.action === 'training.trade')
  expect(trade.map((event: any) => event.phase)).toEqual(['started', 'finished'])
  expect(trade[1].outcome).toBe('accepted')
  // 初始检查点带训练元数据（紧凑文件存引用，解码后可还原快照）；检查点与事件流的交易一致
  expect(file.checkpoints[0].afterSeq).toBe(0)
  expect(file.checkpoints[0].training?.metaRef).toBeTruthy()
  const reader = new CompactReader(file)
  expect(reader.checkpointAt(0).training?.training).toBeTruthy()
  const last = reader.checkpointAt(file.checkpoints.length - 1)
  expect(last.training?.trades.map((item: any) => item.side)).toEqual(['buy'])
  // 导出仅 gzip：不再有「更多导出方式」入口与可读 JSON 按钮
  await expect(page.getByLabel('更多录制导出方式')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '导出可读 JSON' })).toHaveCount(0)
})

test('默认录制交易拒单、周期和画线，暂停恢复后可导出并离线只读回放', async ({ page }) => {
  const active = (await (await page.request.get('/api/trainings/active')).json()).training
  if (active) await page.request.post(`/api/trainings/${active.id}/abandon`)
  await page.goto('/')
  await expect(page.getByLabel('记录操作', { exact: true })).toBeChecked()
  await page.getByPlaceholder('搜索代码或名称，如 600519 或 贵州茅台').fill('600519')
  await page.getByRole('button', { name: /600519 贵州茅台/ }).click()
  await page.locator('input[type="date"]').fill('2026-09-01')
  await startTrainingFromForm(page)
  await expect(page.getByRole('status').filter({ hasText: '正在记录' })).toBeVisible()
  await page.getByRole('button', { name: '买入', exact: true }).click()
  await expect(page.locator('.status-message')).toContainText(/成交|买入/)
  await expect(page.getByRole('button', { name: '刷新图表', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '卖出', exact: true }).click()
  await expect(page.locator('.status-message')).toHaveClass(/error-text/)
  await page.getByRole('button', { name: '推进下一日', exact: true }).click()
  await page.getByRole('tab', { name: '周K', exact: true }).click()
  await expect(page.locator('.timeframe-tabs [aria-selected="true"]')).toHaveText('周K')
  await expect(page.getByRole('button', { name: '刷新图表', exact: true })).toBeEnabled()
  await page.getByRole('tab', { name: '月K', exact: true }).click()
  await expect(page.locator('.timeframe-tabs [aria-selected="true"]')).toHaveText('月K')
  await expect(page.getByRole('button', { name: '刷新图表', exact: true })).toBeEnabled()
  await page.getByRole('tab', { name: '日K', exact: true }).click()
  await expect(page.locator('.timeframe-tabs [aria-selected="true"]')).toHaveText('日K')
  await expect(page.getByRole('button', { name: '刷新图表', exact: true })).toBeEnabled()
  await page.locator('.draw-toolbar').getByRole('button', { name: '线段', exact: true }).click()
  const host = await page.locator('.chart-host').boundingBox()
  await page.mouse.click(host!.x + host!.width * .35, host!.y + 140)
  await page.waitForTimeout(550)
  await page.mouse.click(host!.x + host!.width * .55, host!.y + 180)
  await expect.poll(() => page.evaluate(() => (window as any).__trainerChart.drawings().length)).toBe(1)
  await expect(page.locator('.drawing-save-status')).toHaveText('已保存')
  await page.getByLabel('记录操作', { exact: true }).uncheck()
  await expect(page.getByRole('status').filter({ hasText: '已暂停记录' })).toBeVisible()
  await page.getByRole('tab', { name: '周K', exact: true }).click()
  await page.getByLabel('记录操作', { exact: true }).check()
  await expect(page.getByRole('status').filter({ hasText: '正在记录' })).toBeVisible()
  await page.screenshot({ path: evidencePath('recording-training-dark.png') })
  await page.getByRole('button', { name: '切换到浅色主题', exact: true }).click()
  await page.setViewportSize({ width: 1280, height: 800 })
  await expect(page.getByRole('status').filter({ hasText: '正在记录' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: evidencePath('recording-training-light.png') })
  await page.getByRole('button', { name: '切换到深色主题', exact: true }).click()
  await page.setViewportSize({ width: 1440, height: 900 })
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出录制', exact: true }).click()
  const download = await pending
  const output = evidencePath('recorded-session.json.gz')
  await download.saveAs(output)
  expect([...(await readFile(output)).subarray(0, 2)]).toEqual([0x1f, 0x8b])
  const recording = await readRecordingArtifact(output)
  expect(recording.format).toBe('trainer-session')
  expect(recording.app.gitCommit).not.toBe('unknown')
  expect(recording.events.some((e: any) => e.action === 'training.trade' && e.outcome === 'accepted')).toBe(true)
  expect(recording.events.some((e: any) => e.action === 'training.trade' && e.outcome === 'rejected')).toBe(true)
  expect(recording.events.some((e: any) => e.action === 'chart.drawing.create')).toBe(true)
  // 新采集固定 1D 权威行情（REC-02）：周期切换只作用于界面，检查点不随视图周期变化
  const charted = recording.checkpoints.filter((c: any) => c.chart)
  expect(charted.length).toBeGreaterThan(0)
  expect(charted.every((c: any) => c.chart.timeframe === '1D')).toBe(true)
  // 无噪音事件：创建样板/加载/周期/视口/工具/保存/主题都不再进入录制事件流
  for (const noise of ['training.create', 'chart.load', 'chart.timeframe', 'chart.viewport', 'chart.tool', 'drawings.save', 'ui.theme']) {
    expect(recording.events.some((e: any) => e.action === noise)).toBe(false)
  }
  expect(recording.gaps.length).toBeGreaterThan(0)
  await settleThroughConfirmation(page)
  // Replay must consume the file even if all backend endpoints are unavailable.
  await page.getByRole('button', { name: '训练录像', exact: true }).click()
  await expect(page.getByRole('heading', { name: '训练录像', exact: true })).toBeVisible()
  await page.route('**/api/**', route => route.abort())
  await page.getByLabel('导入录制', { exact: true }).setInputFiles(output)
  await expect(page.getByRole('button', { name: '关闭回放', exact: true })).toBeVisible()
  const writes: string[] = []
  page.on('request', request => { if (/\/api\//.test(request.url()) && ['POST', 'PUT', 'DELETE'].includes(request.method())) writes.push(request.url()) })
  // REC-03 按日回放：跳到最后一天；日期轴如实显示第 n / N 日
  await page.getByRole('button', { name: '跳到最后一天' }).click()
  await expect(page.locator('.replay-day')).toHaveText(/第 \d+ \/ \d+ 日/)
  await expect.poll(() => page.evaluate(() => (window as any).__trainerChart?.drawings().length ?? 0)).toBeGreaterThan(0)
  const drawingsBefore = await page.evaluate(() => (window as any).__trainerChart.drawings())
  await expect(page.getByRole('button', { name: '买入', exact: true })).toHaveCount(0)
  await page.keyboard.press('b')
  await page.keyboard.press('Delete')
  const replayHost = await page.locator('.chart-host').boundingBox()
  await page.mouse.click(replayHost!.x + 260, replayHost!.y + 150, { button: 'right' })
  expect(await page.evaluate(() => (window as any).__trainerChart.drawings())).toEqual(drawingsBefore)
  await page.screenshot({ path: evidencePath('recording-replay.png') })
  await page.getByRole('button', { name: '切换到浅色主题', exact: true }).click()
  await page.setViewportSize({ width: 1280, height: 800 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: evidencePath('recording-replay-light.png') })
  expect(writes).toEqual([])
})

test('浏览器存储恢复后可重试录制，错误不伪装成正在记录', async ({ page }) => {
  const active = (await (await page.request.get('/api/trainings/active')).json()).training
  if (active) await page.request.post(`/api/trainings/${active.id}/abandon`)
  await page.addInitScript(() => {
    const open = indexedDB.open.bind(indexedDB)
    ;(window as any).__recordingStorageFault = true
    indexedDB.open = (...args: Parameters<IDBFactory['open']>) => {
      if ((window as any).__recordingStorageFault) throw new DOMException('storage temporarily unavailable', 'UnknownError')
      return open(...args)
    }
  })
  await page.goto('/')
  await page.getByPlaceholder('搜索代码或名称，如 600519 或 贵州茅台').fill('600519')
  await page.getByRole('button', { name: /600519 贵州茅台/ }).click()
  await page.locator('input[type="date"]').fill('2026-09-01')
  await startTrainingFromForm(page)
  await expect(page.getByRole('status').filter({ hasText: '记录失败' })).toBeVisible()
  await page.evaluate(() => { (window as any).__recordingStorageFault = false })
  await page.getByRole('button', { name: '重试录制保存' }).click()
  await expect(page.getByRole('status').filter({ hasText: '正在记录' })).toBeVisible()
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出录制', exact: true }).click()
  const download = await pending
  const output = evidencePath('storage-recovery-session.json')
  await download.saveAs(output)
  const file = await readRecordingArtifact(output)
  expect(file.gaps.length).toBeGreaterThan(0)
  expect(file.gaps.at(-1).resumedAtSeq).not.toBeNull()
  await page.screenshot({ path: evidencePath('recording-storage-recovered.png') })
})

test('首页关闭仅影响本场，刷新保留暂停且恢复后可导出', async ({ page }) => {
  test.setTimeout(60_000)
  const active = (await (await page.request.get('/api/trainings/active')).json()).training
  if (active) await page.request.post(`/api/trainings/${active.id}/abandon`)
  await page.goto('/')
  await expect(page.getByLabel('记录操作', { exact: true })).toBeChecked()
  await page.getByLabel('记录操作', { exact: true }).uncheck()
  await page.getByPlaceholder('搜索代码或名称，如 600519 或 贵州茅台').fill('600519')
  await page.getByRole('button', { name: /600519 贵州茅台/ }).click()
  await page.locator('input[type="date"]').fill('2026-09-01')
  await startTrainingFromForm(page)
  await expect(page.getByRole('status').filter({ hasText: '已暂停记录' })).toBeVisible()
  await page.reload()
  await expect(page.locator('.training-topbar')).toBeVisible({ timeout: 30_000 })
  await expect(page.getByRole('status').filter({ hasText: '已暂停记录' })).toBeVisible()
  await page.getByLabel('记录操作', { exact: true }).check()
  await expect(page.getByRole('status').filter({ hasText: '正在记录' })).toBeVisible()
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出录制', exact: true }).click()
  const download = await pending
  const output = evidencePath('initially-paused-session.json')
  await download.saveAs(output)
  const file = await readRecordingArtifact(output)
  expect(file.gaps[0].afterSeq).toBe(0)
  expect(file.gaps[0].resumedAtSeq).toBeGreaterThan(0)
  await settleThroughConfirmation(page)
  await expect(page.getByLabel('记录操作', { exact: true })).toBeChecked()
})
